runtime: python27
api_version: 1
threadsafe: true

handlers:
 - url: /
   static_files: index.html
   upload: index.html

 - url: /(.*.html)
   static_files: \1
   upload: (.*.html)

 - url: /js/(.*)
   static_files: js/\1
   upload: js/(.*)

 - url: /css/(.*)
   static_files: css/\1
   upload: css/(.*)


 - url: /img/(.*)
   static_files: img/\1
   upload: img/(.*)

 - url: /favicon.ico
   static_files: favicon.ico
   upload: favicon.ico

 - url: /node_modules/bootstrap/dist/css/(.*)
   static_files: node_modules/bootstrap/dist/css/\1
   upload: node_modules/bootstrap/dist/css/(.*)
