runtime: python27
api_version: 1
threadsafe: true

handlers:
 - url: /
   static_files: index.html
   upload: index.html

 - url: /js/(.*)
   static_files: js/\1
   upload: js/(.*)

 - url: /css/(.*)
   static_files: css/\1
   upload: css/(.*)


 - url: /img/(.*)
   static_files: img/\1
   upload: img/(.*)  
