runtime: python27
api_version: 1
threadsafe: true

handlers:
 - url: /
   static_files: welcome.html
   upload : welcome.html

 - url: /privacy.html
   static_files: privacy.html
   upload : privacy.html

 - url: /secretLocation
   static_files: www/index.html
   upload : www/index.html

 - url: /js/(.*)
   static_files: www/js/\1
   upload: www/js/(.*)

 - url: /css/(.*)
   static_files: www/css/\1
   upload: www/css/(.*)


 - url: /img/(.*)
   static_files: www/img/\1
   upload: www/img/(.*)

 - url: /imgLarge/(.*)
   static_files: imgLarge/\1
   upload: imgLarge/(.*)

 - url: /snd/(.*)
   static_files: www/snd/\1
   upload: www/snd/(.*)

 - url: /favicon.ico
   static_files: favicon.ico
   upload: favicon.ico

 - url: /node_modules/bootstrap/dist/css/(.*)
   static_files: www/node_modules/bootstrap/dist/css/\1
   upload: www/node_modules/bootstrap/dist/css/(.*)   

# files to skip when uploading
# note if we have too many files to upload, we might get an error
# note if we have too many versions (>=15), u can remove them at
# https://console.cloud.google.com/appengine/versions
skip_files:
 - node_modules/
 - plugins/
 - platforms/
 